version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-nest-template
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
    networks:
      - dev_network

volumes:
  db_data_dev:

networks:
  dev_network:
